anguage: node_js
node_js:
  - 11.6.0
cache: npm


install:
  - npm install
  
script:
  - docker push vitorcastillo/bdd-test
  - docker run -v $PWD/:/app/report/ vitorcastillo/bdd-test

# after_script:
#   - bash ./telegram_notification.sh
  
  
after_success:

  - ls  
  - chmod +x final_report.sh
  - . final_report.sh
  
  - git init
  - git config user.name "Travis CI"
  - git config user.email "travis@travis.org"
  #- git add /report/cucumber_report.html
  - git add cucumber_report.html
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://michelleamesquita:${GITHUB_API_KEY}@${GH_REF}" main:gh-pages > /dev/null 2>&1
  - echo $RESULT
  
  
  
